---
extends:
  - 'react-app'
  - 'prettier/@typescript-eslint'
#  - 'plugin:@typescript-eslint/recommended' # TODO: uncomment and fix all eslint warnings/errors separately

parser:
  '@typescript-eslint/parser'

plugins:
  - import
#  - '@typescript-eslint' # TODO: uncomment and fix all eslint warnings/errors separately

rules:

  semi: 2
  indent: [1, 2, {"SwitchCase": 1}]
  react/jsx-indent: [1, 2]
  react/jsx-wrap-multilines: 2
  comma-dangle:
    - 2
    - never
  no-cond-assign: 2
  no-extra-boolean-cast: 2
  no-extra-parens:
    - 0
  no-extra-semi: 2
  no-irregular-whitespace: 2
  no-negated-in-lhs: 2
  no-reserved-keys: 0
  use-isnan: 2

  valid-jsdoc: 0
  valid-typeof: 2

  # http://eslint.org/docs/rules/#best-practices
  accessor-pairs:
    - 2
    - getWithoutSet: false
      setWithoutGet: true
  complexity: 0
  consistent-return: 0
  curly:
    - 2
    - all
  dot-location:
    - 2
    - property
  no-div-regex: 0
  no-else-return: 2
  labeled: 0
  no-floating-decimal: 2
  no-multi-spaces: 2
  no-native-reassign: 2
  no-param-reassign: 0
  no-process-env: 0
  no-return-assign: 2
  no-unused-expressions: 2
  vars-on-top: 0
  wrap-iife:
    - 2
    - outside

  strict:
    - 2
    - global

  # http://eslint.org/docs/rules/#variables
  # Can't occur, because 'no-labels' is enabled.
  no-label-var: 0
  no-shadow: 2
  no-undef: 2
  no-undefined: 0
  no-unused-vars:
    - 2
    - vars: all
      args: after-used

  # http://eslint.org/docs/rules/#nodejs
  callback-return: 2
  global-require: 2
  handle-callback-err:
    - 2
    - ^(e|err|error)$
  no-mixed-requires:
    - 2
    - true
  no-new-require: 2
  no-path-concat: 2
  no-process-exit: 2
  no-restricted-modules: 0
  no-sync: 0

  # http://eslint.org/docs/rules/#stylistic-issues
  brace-style:
    - 2
    - 1tbs
    - allowSingleLine: false
  camelcase:
    - 2
    - properties: always
  comma-spacing:
    - 2
    - before: false
      after: true
  comma-style:
    - 2
    - last
  computed-property-spacing:
    - 2
    - never
  consistent-this:
    - 0
  eol-last: 2
  func-names: 0

  # http://eslint.org/docs/rules/keyword-spacing.html
  keyword-spacing:
    - 2
    - before: true
      after: true
      overrides: { }
  key-spacing:
    - 2
    - beforeColon: false
      afterColon: true
  lines-around-comment: 0
  linebreak-style:
    - 2
    - unix
  new-parens: 2
  newline-after-var: 0
  # Implied by 'indent'
  no-mixed-spaces-and-tabs: 0
  no-multiple-empty-lines:
    - 2
    - max: 2
  no-spaced-func: 2
  no-ternary: 0
  no-trailing-spaces: 2
  no-underscore-dangle: 0
  no-unneeded-ternary: 2
  object-curly-spacing:
    - 2
    - always
  one-var:
    - 2
    - never
  operator-assignment:
    - 2
    - always
  operator-linebreak:
    - 2
    - after
  padded-blocks:
    - 2
    - never
  quote-props:
    - 2
    - as-needed
  quotes:
    - 2
    - single
    - avoid-escape
  semi-spacing:
    - 2
    - before: false
      after: true
  sort-vars:
    - 2
    - ignoreCase: true
  space-before-blocks:
    - 2
    - always
  space-before-function-paren:
    - 2
    - never
  space-in-parens:
    - 2
    - never
  space-infix-ops: 2
  space-unary-ops:
    - 2
    - words: true
      nonwords: false
  spaced-comment:
    - 1
    - always
  wrap-regex: 0

  # http://eslint.org/docs/rules/#legacy
  max-len:
    - 0
    - 120
    - 4
    - ignoreComments: false
      ignoreUrls: true

  no-alert: 2
  no-array-constructor: 2
  no-bitwise: 2
  no-caller: 2
  no-case-declarations: 2
  no-class-assign: 2
  no-console: 2
  no-const-assign: 2
  no-constant-condition: 2
  no-continue: 2
  no-control-regex: 2
  no-debugger: 2
  no-delete-var: 2
  no-dupe-class-members: 2
  no-dupe-keys: 2
  no-dupe-args: 2
  no-duplicate-case: 2
  no-empty: 2
  no-empty-character-class: 2
  no-empty-pattern: 2
  no-eq-null: 2
  no-eval: 2
  no-ex-assign: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-fallthrough: 2
  no-func-assign: 2
  no-implicit-coercion: 2
  no-implied-eval: 2
  no-inline-comments: 2
  no-inner-declarations: 2
  no-invalid-regexp: 2
  no-invalid-this: 2
  no-iterator: 2
  no-labels: 2
  no-lone-blocks: 2
  no-lonely-if: 2
  no-loop-func: 2
  no-multi-str: 2
  no-global-assign: 2
  no-negated-condition: 2
  no-nested-ternary: 2
  no-new: 2
  no-new-func: 2
  no-new-object: 2
  no-new-wrappers: 2
  no-obj-calls: 2
  no-octal: 2
  no-octal-escape: 2
  no-plusplus: 2
  no-proto: 2
  no-regex-spaces: 2
  no-script-url: 2
  no-self-compare: 2
  no-sequences: 2
  no-shadow-restricted-names: 2
  no-sparse-arrays: 2
  no-this-before-super: 2
  no-throw-literal: 2
  no-undef-init: 2
  no-unreachable: 2
  no-use-before-define: 2
  no-useless-call: 2
  no-useless-concat: 2
  no-void: 2
  no-var: 2
  no-warning-comments: 2
  no-with: 2
  block-scoped-var: 2
  constructor-super: 2
  default-case: 2
  dot-notation: 2
  eqeqeq: 2
  guard-for-in: 2
  id-length: 2
  max-depth: 2
  max-nested-callbacks: 2
  max-params: 2
  new-cap: 2
  object-shorthand: 2
  prefer-const: 2
  prefer-spread: 2
  prefer-template: 2
  radix: 2
  require-yield: 2
  yoda: 2
  no-empty-function: 2
  no-new-symbol: 2
  no-unmodified-loop-condition: 2
  prefer-rest-params: 2
  no-extra-label: 2
  no-unused-labels: 2
  no-useless-constructor: 2
  no-useless-escape: 2
  max-statements-per-line: 2
  no-duplicate-imports: 2
  no-unsafe-finally: 2
  no-useless-computed-key: 2
  no-useless-rename: 2
  max-lines: 2
  no-template-curly-in-string: 2
  symbol-description: 2
  class-methods-use-this: 2
  prefer-numeric-literals: 2
  line-comment-position: 2
  no-useless-return: 2
  no-return-await: 2
  require-await: 2
  no-await-in-loop: 2
  prefer-destructuring: 2
  no-multi-assign: 2
  no-compare-neg-zero: 2
  for-direction: 2
  no-buffer-constructor: 2
  getter-return: 2
  lines-between-class-members: 2
  max-classes-per-file: 2
  no-misleading-character-class: 2
  require-atomic-updates: 2
  no-async-promise-executor: 2
  require-unicode-regexp: 2
  no-useless-catch: 2
  prefer-named-capture-group: 2
  no-redeclare: 2
  no-prototype-builtins: 2
  no-import-assign: 2
  prefer-regex-literals: 2
  default-param-last: 2
  no-constructor-return: 2
  no-dupe-else-if: 2
  no-setter-return: 2
  prefer-exponentiation-operator: 2
  prefer-object-spread: 2
  init-declarations: 2
  import/named: 2
  import/default: 2
  import/namespace: 2
  import/no-absolute-path: 2
  import/no-dynamic-require: 2
  import/no-webpack-loader-syntax: 2
  import/no-self-import: 2
  import/export: 2
  import/no-named-as-default: 2
  import/no-named-as-default-member: 2
  import/no-deprecated: 2
  import/no-mutable-exports: 2
  import/unambiguous: 2
  import/no-amd: 2
  import/first: 2
  import/exports-last: 2
  import/no-duplicates: 2
  import/no-namespace: 2
  import/newline-after-import: 2
  import/no-unassigned-import: 2
  import/no-named-default: 2
  import/no-anonymous-default-export: 2
  import/group-exports: 2
  import/no-unresolved: 2
